version: "3.9"

services:
    web:
        container_name: laravel07_nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - fpm
            - mysql

    fpm:
        container_name: laravel07_fpm
        environment:
            PHP_IDE_CONFIG: "serverName=laravel07"
        build:
          dockerfile: docker/php/Dockerfile
          context: .
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        links:
            - mysql
    mysql:
        container_name: laravel07_db
        image: mariadb:10.3
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel07
#    my_frontend:
#        container_name: my_frontend
#        image: node:lts
#        working_dir: /var/www/html
#        entrypoint: /bin/bash
#        ports:
#            - "8000:8000"
#        volumes:
#            - ./:/var/www/html
#        tty: true
#
